{
  lib,
  systemName,
  ...
}: {
  imports = [
    ./archive-utils.nix
    ./audio-video
    ./bat.nix
    ./btop.nix
    ./borg.nix
    ./bulkrename.nix
    ./comma.nix
    ./exiftool.nix
    ./eza.nix
    ./fd.nix
    ./fetch.nix
    ./gping.nix
    ./jq.nix
    ./killall.nix
    ./ncdu.nix
    ./procs.nix
    ./rink.nix
    ./ripgrep.nix
    ./rsync.nix
    ./rust-nix-shell.nix
    ./sad.nix
    ./scripts.nix
    ./speedtest.nix
    ./tmux.nix
    ./watch.nix
    ./wget.nix
    ./xattr.nix
  ];
}
